---
apiVersion: v1
kind: Service
metadata:
  name: ebookclub
  labels:
    app: ebookclub
spec:
  type: NodePort
  selector:
    app: ebookclub
  ports:
    - protocol: TCP
      port: 8187
      name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ebookclub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ebookclub
    spec:
      containers:
        - name: ebookclub
          image: shereen/ebookclub:1.1
          ports:
            - containerPort: 8187
          livenessProbe:
            httpGet:
              path: /book
              port: 8187
            initialDelaySeconds: 30
            timeoutSeconds: 1
